### ISSUE TITLE
Toggling paired HTML entities not working

### ISSUE THREAD

**Issue by certainlyakey** [gordio/ToggleWords#10]
The punctuation by the sides of a word stops toggling from working. For instance, this won't toggle even when cursor is placed right inside the word: 

    ["&laquo;", "&raquo;"],
    ["&larr;", "&rarr;"],

However, an easy workaround is to define the central part of entities, for example, `laquo` and `raquo` (without `&` and `;`) in ToggleWords dictionary.

**Comment by gordio** [comment]
All right. ToggleWords use sublime.view.substr(region). Selection work like predefined. Sorry about that. But thx, I add this to README.md.

**Comment by certainlyakey** [comment]
Thanks for clearing that out)

**Comment by gordio** [comment]
Thank you for report!
It you interested in change reaction, you can check `word_separators` option in `Preferences.sublime-settings` file.
