### ISSUE TITLE
Cycle order incorrect

### ISSUE THREAD

**Issue by FeBe95** [gordio/ToggleWords#14]
My user settings extend the color array to:
`["red", "orange", "yellow", "green", "blue", "purple", "black", "white"]`
However the resulting order is:
`orange -> yellow -> purple -> green -> black -> white -> blue -> red -> ...`

The array
`["123", "4250", "122", "20", "010", "215"]`
results in
`4250 -> 123 -> 122 -> 010 -> 215 -> 20 -> ...` 

They seem to be sorted by word length (and alphabetically?). Is this intentional? The ReadMe says
>"You can define lists of words, which will be cycled through in order."

**Comment by gordio** [comment]
@FeBe95 thx, Sorting removed in #0b80b70 commit.
